version: '3.9'

services:
  app:
    build:
      args:
        NODE_VERSION: 18
        USERNAME: vscode
        VARIANT: 8.2-bullseye
    env_file: ../.env
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - node-modules:/workspace/node_modules
      - pnpm-store:/workspace/.pnpm-store
      # Directory is created with Dockerfile
      - vscode-extensions:/home/vscode/.vscode-server/extensions
    network_mode: service:postgres

  postgres:
    image: postgres:14.6-alpine
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../config/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  node-modules:
  pnpm-store:
  postgres_data:
  vscode-extensions:
