name: Patch

permissions: {}

on:
  pull_request:
    types:
      - closed

jobs:
  patch:
    if: github.event.pull_request.merged == true
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - name: 🦜 Bump up version
        run: |
          git config --global user.name "Release Parrot"
          git config --global user.email release.parrot@bump.patch
          npx bumpp patch --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
